### PR TITLE
"*" itself is a key

### PR DESCRIPTION
**Pull request by Jxck**
from bnf and 4.1.1.3
`*` itself is a key

```
key = ( lcalpha / "*" ) *( lcalpha / DIGIT / "_" / "-" / "." / "*")
```

### CODE REVIEW

**Comment by phluid61** [comment]
You shouldn't add cases directly to any 'generated' JSON files. Have a look at `generate.py` instead.

**Comment by Jxck** [comment]
I fixed generated.py and re-generate json.
I think this case is standalone so append directory to tests obj.

**Comment by mnot** [comment]
Hey @Jxck -

If you're looking to verify that a single-character key is valid, it'd probably be good to generate test cases for *all* single-character keys, rather than just one.

I think that's something like

~~~ python
## single-character dictionary keys
for c in ALL_CHARS:
    test = {
        "name": "0x%02x as a single-character dictionary key" % c,
        "raw": ["%s=1" % chr(c)],
        "header_type": "dictionary",
    }
    if c in allowed_key_start_chars:
        test["expected"] = [["%s" % chr(c), [1, []]]]
    else:
        test["must_fail"] = True
    tests.append(test)
~~~

(although whitespace might need special handling)

**Comment by Jxck** [comment]
@mnot seems reasonable, I'll handle it.

**Comment by Jxck** [comment]
there are some choice for 0x20 (space)

1. just leave it as test case (`" =1"`)
2. strip space and use as test case (`"=1"`)
3. just remove from testing because `"=1"` is not a test case for *key format*

now I'm on 2 but comments are welcome.

**Comment by mnot** [comment]
+1 (2) makes sense

**Comment by mnot** [comment]
@jxck is this ready to go? Anyone else with comments / concerns?

**Comment by Jxck** [comment]
It's on 2 so I think fine.

**Pull request merged**
