### PR TITLE
fix: use JSON arrays instead of objects to preserve order

### LINKED ISSUE #48: Parameters shouldn't be stored as JSON objects
By the SFV spec, parameters are ordered:

> Parameters are an ordered map of key-value pairs that are associated with an Item (Section 3.3) or Inner List (Section 3.1.1).

However, by the JSON spec, JSON objects aren't ordered:

> An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number,  boolean, null, object, or array.

Several JSON parsers (including the JSON parser included in the standard library of Go: https://github.com/golang/go/issues/27179) aren't able to preserve the order, and make the test suite hard to use. An array of arrays (or of objects) should be used instead.

### PR DESCRIPTION
**Pull request by dunglas**
Fixes #48.

I tested this change using my Go implementation (to be released soon).

### CODE REVIEW

**Comment by phluid61** [comment]
I've looked at the diff and it seems good, but I don't have the mental fortitude to check every single line. If it works against an implementation I'm happy.

(I won't be able to update my implementation right away to triple-check)

**Comment by mnot** [comment]
Same :)  I'll do an update to mine soon and check this branch with it.

**Comment by dunglas** [comment]
I confirm that it works with my implementation but double-checking with at least another implementation would indeed be better!

**Comment by mnot** [comment]
Works for me, and a very easy change -- https://github.com/mnot/http_sfv/pull/5. Thanks!

**Comment by gapple** [comment]
Was able to update my PHP implementation's tests to work with the new format

**Pull request merged**
